server:
  port: 8982
spring:
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver        # mysql驱动
    url: jdbc:mysql://118.190.56.57:3307/shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: lq129011
    username: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  rabbitmq:
    addresses: 192.168.52.130:5672
    username: admin
    password: admin
    virtual-host: /lq_host
    connection-timeout: 3000ms
    listener:
      simple:
        acknowledge-mode: manual # 默认为AUTO 这里选择MANUAL表示消费消息成功后 需要手动进行你签收（ack）。
        concurrency: 1
        max-concurrency: 3
        prefetch: 1
  application:
    name: rabbit-consumer
